name: sip_app
description: "SIP softphone app Asterisk alapú hívásokhoz"
publish_to: 'none'

version: 1.0.2+4

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sip_ua: ^1.1.0
  flutter_webrtc: ^1.0.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  flutter_contacts: ^2.2.0
  flutter_callkit_incoming: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
